### ISSUE TITLE
Can't switch my IMac to Target Display Mode

### ISSUE THREAD

**Issue by zhouzizi** [duanefields/VirtualKVM#38] opened 2017-04-18 04:39 UTC
The Host Mode is 'Connetcted',but can't automatically switch mode.
I can switch it use Keyboard..

**Comment by SoneeJohn** [comment] 2017-04-18 20:08
@zhouzizi can you please try this build: https://github.com/SoneeJohn/VirtualKVM/releases/download/v1.2.2/VirtualKVM.zip

Let me know if that solves your issue.

**Comment by SoneeJohn** [comment] 2017-04-18 20:08
I believe this is a duplicate of: https://github.com/duanefields/VirtualKVM/issues/24

**Comment by zhouzizi** [comment] 2017-04-19 03:07
My iMac system version is 10.12 ，I have try [https://github.com/SoneeJohn/VirtualKVM/releases/download/v1.2.2/VirtualKVM.zip](v1.2.2/VirtualKVM.zip) and [https://github.com/alvaromurillo/VirtualKVM/releases/tag/1.1.3](v1.1.3), It doesn't work both.
I do not know if there is some problem with my running mode, the iMac doesn't have a keyboard ,only a mouse.And I connect MacBook Pro and iMac with Thunderbolt, and my iMac run the VirtualKVM,I think this time it will switch to TDM, but it didn't...
Where is the problem....

**Comment by SoneeJohn** [comment] 2017-04-19 14:40
@zhouzizi The iMac will need to have a keyboard connected to it.

**Comment by zhouzizi** [comment] 2017-04-19 14:43
The iMac have a normal keyboard ,but not apple bluetooth keyboard.Can it work？

**Comment by SoneeJohn** [comment] 2017-04-19 14:45
@zhouzizi I believe it needs to have an Apple keyboard, if I can recall correctly.

**Comment by imyelmo** [comment] 2017-04-19 14:57
I 'am experiencing the problem and I have a Bluetooth Apple Keyboard.

**Comment by csandeep** [comment] 2017-07-28 01:40
Just chiming in -- the `v1.2.2` works on late-2013 iMac + 2017 MBP running `macOS Sierra`

**Closed** 2017-11-20 19:09 UTC
